sudo: required
services:
        - docker

before_install:
        - docker build -t shonry27/docker-react -f Dockerfile.dev .

script:
        - docker run shonry27/docker-react npm run test -- --coverage

